Fix long task duration extraction
DataDog/dd-bridge-android pull request #41
Opened 2021-10-04 12:51 UTC by 0xnm

### What does this PR do?

This change fixed extraction of the long task duration value: in JS all the numbers are floating-point numbers, so when any number (even written without floating part) comes to JVM layer, it has `Double` type and cast to `Long` always fails.

This change fixes this issue by casting to the common parent of all numbers type - `Number` (so that code could work for other frameworks, which can pass `Int` or `Long`) and then getting `Long` value.

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2021-10-04 12:56 UTC, mariusc83 approved these changes

2021-10-04 12:56 UTC, mariusc83 commented on dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/internal/BridgeSdk.kt
> +            (configuration.additionalConfig?.get(DD_LONG_TASK_THRESHOLD) as? Number)?.toLong()
What was actually the problem here ?

2021-10-04 13:58 UTC, xgouchet requested changes

2021-10-04 13:58 UTC, xgouchet commented on dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/internal/BridgeSdk.kt
> -        val longTask = configuration.additionalConfig?.get(DD_LONG_TASK_THRESHOLD) as? Long
Can we add a test for this scenario please ?

2021-10-05 09:50 UTC, xgouchet approved these changes

2021-10-05 09:53 UTC, merged